[package]
name = "v7"
version = "0.1.0"
edition = "2021"

[dependencies]
b15r = { path = "./crates/b15r/" }
indicatif = "0.17.9"
reed-solomon = "0.2.1"
serialport = "4.6.0"
ansi_term = "0.12.1"
colored = "2.1.0"
chrono = "0.4.39"

[features]
b15f = []
arduino = []
