pub const SOT: u8 = 0b111; //  7 Start of transmission
pub const SOTH: u8 = 0b0101; //  5 Start of transmission header
pub const EOT: u8 = 0b100; //  4 End of transmission
pub const SOH: u8 = 0b1; //  1 Start of header
pub const SOTX: u8 = 0b10; //  2 Start of text
                           // pub const EOTX: u8  = 0b11;   //  3 End of text
                           //pub const ENQ:  u8  = 0b101;   //  5 Enquiry
                           //pub const ACK:  u8  = 0b110;   //  6 Acknowledge
                           //pub const NAC:  u8  = 0b10101; // 21 Not acknowledge
